# Site wide configuration

title: "SKM Professional Services"
description: "'Your way up!'"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: SKM Professional Services

#Target date in UTC / GMT
countdown:
  theme: red
  year: 2017
  month: 04
  day: 31
  hour: 12
  minute: 0

# Site owner
owner:
  name: SKM Professional Services
  email: info-at-skmprofessionalservices.nl 
  email-body: Attention:%20please%20remove%20%22-at-%22%20from%20the%20e-mail%20address%20and%20replace%20it%20with%20%22@%22 
  twitter:
  google-plus:
  instagramm:
  #Aboutlink = German "Impressum", provide url and caption (eg "Impressum")
  aboutlink:
    url:
    caption:


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
